### ISSUE TITLE
Thread terminated with exception when running specs with webmock

### ISSUE THREAD

**Issue by Hirurg103** [newrelic/rpm#335]
I am blocking external requests in rspec specs with [webmock](https://github.com/bblimke/webmock):

```ruby
WebMock.disable_net_connect!(allow: /(127\.0\.0\.1|localhost/)
```

After I upgraded ruby to `v2.5.8` I started seeing the following error in rspec output:

```
#<Thread:0x00007fcb1d440b98@~/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent/threading/agent_thread.rb:12 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	26: from ~/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent/threading/agent_thread.rb:14:in `block in create'
	25: from ~/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent/agent.rb:718:in `block in start_worker_thread'
	24: from ~/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent/agent.rb:691:in `deferred_work!'
	23: from ~/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent/agent.rb:672:in `catch_errors'
	22: from ~/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent/agent.rb:692:in `block in deferred_work!'
	21: from ~/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent.rb:506:in `disable_all_tracing'
	20: from ~/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent/agent.rb:693:in `block (2 levels) in deferred_work!'
	19: from ~/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent/agent.rb:940:in `connect'
	18: from ~/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent/agent.rb:821:in `connect_to_server'
	17: from ~/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent/connect/request_builder.rb:37:in `connect_payload'
	16: from ~/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent/utilization_data.rb:77:in `to_collector_hash'
	15: from ~/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent/utilization_data.rb:89:in `append_vendor_info'
	14: from ~/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent/utilization_data.rb:89:in `each_pair'
	13: from ~/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent/utilization_data.rb:93:in `block in append_vendor_info'
	12: from ~/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent/utilization/vendor.rb:46:in `detect'
	11: from ~/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent/utilization/vendor.rb:65:in `request_metadata'
	10: from ~/.rbenv/versions/2.5.8/lib/ruby/2.5.0/timeout.rb:108:in `timeout'
	 9: from ~/.rbenv/versions/2.5.8/lib/ruby/2.5.0/timeout.rb:33:in `catch'
	 8: from ~/.rbenv/versions/2.5.8/lib/ruby/2.5.0/timeout.rb:33:in `catch'
	 7: from ~/.rbenv/versions/2.5.8/lib/ruby/2.5.0/timeout.rb:33:in `block in catch'
	 6: from ~/.rbenv/versions/2.5.8/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
	 5: from ~/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent/utilization/vendor.rb:67:in `block in request_metadata'
	 4: from ~/.rbenv/versions/2.5.8/lib/ruby/2.5.0/net/http.rb:609:in `start'
	 3: from ~/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/webmock-3.4.2/lib/webmock/http_lib_adapters/net_http.rb:150:in `start'
	 2: from ~/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/webmock-3.4.2/lib/webmock/http_lib_adapters/net_http.rb:123:in `start_without_connect'
	 1: from ~/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent/utilization/vendor.rb:69:in `block (2 levels) in request_metadata'
~/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/webmock-3.4.2/lib/webmock/http_lib_adapters/net_http.rb:114:in `request': Real HTTP connections are disabled. Unregistered request: GET http://169.254.169.254/2016-09-02/dynamic/instance-identity/document with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Host'=>'169.254.169.254', 'User-Agent'=>'Ruby'} (WebMock::NetConnectNotAllowedError)

You can stub this request with the following snippet:

stub_request(:get, "http://169.254.169.254/2016-09-02/dynamic/instance-identity/document").
  with(
    headers: {
	  'Accept'=>'*/*',
	  'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3',
	  'Host'=>'169.254.169.254',
	  'User-Agent'=>'Ruby'
    }).
  to_return(status: 200, body: "", headers: {})
```

Except `http://169.254.169.254/2016-09-02/dynamic/instance-identity/document` newrelic makes requests to the following URLS:

- `http://metadata.google.internal/computeMetadata/v1/instance/?recursive=true`
- `http://169.254.169.254/metadata/instance/compute?api-version=2017-03-01`
- `https://collector.newrelic.com/agent_listener/invoke_raw_method?license_key=&marshal_format=json&method=preconnect&protocol_version=17`
- `https://collector.newrelic.com/agent_listener/invoke_raw_method?license_key=&marshal_format=json&method=connect&protocol_version=17`

I was able to fix the error above with stubbing all requests to requested hosts:

```ruby
# spec/support/global_request_stubs.rb
RSpec.configure do |config|
  config.before(:each) do
    # Newrelic
   stub_request(:get, /169\.254\.169\.254/)
   stub_request(:get, /metadata\.google\.internal/)
   stub_request(:post, /collector\.newrelic\.com/)
  end
end
```

Is there a way to disable newrelic in tests so there is no need to stub requests from newrelic agent?

**Comment by rachelleahklein** [comment]
Hi @Hirurg103! Thanks for reaching out!

For questions about using/configuring the agent, we generally recommend working with our Support team, which can be reached directly though support.newrelic.com.

**Comment by Hirurg103** [comment]
Hi @rachelleahklein , thank you for the fast reply!

OK, I will contact Support team and paste there what they say

**Comment by rachelleahklein** [comment]
Sounds good. I will go ahead and close this issue. Thanks again!

**Comment by Hirurg103** [comment]
There are two ways to stop newrelic agent to send data to newlelic collector:

1. Add `ENV['NEW_RELIC_MONITOR_MODE'] = 'false'` in `config/environments/test.rb`
2. Set ` monitor_mode: false` for the `test` environment in `config/newrelic.yml` (this is the default option when you generate newrelic config for the first time)

See [New Relic documentation for monitor_mode](https://docs.newrelic.com/docs/agents/ruby-agent/configuration/ruby-agent-configuration#monitor_mode) option to get more details

**Comment by mehyedes** [comment]
Hi @rachelleahklein 
I am wondering why the ruby agent needs to request `169.254.169.254` and `metadata.google.internal` at all for self hosted environments. 
We have noticed that those outgoing requests have been affecting our application since they were trying to go through the proxy, so they don't fail early enough, but take ages to time out causing our processes to get stuck.
Please correct me if I am wrong.

**Comment by rachelleahklein** [comment]
Hi, @mehyedes.

By default, the Ruby agent will report cloud vendor metadata to NewRelic during its initial connect. You can disable checks for cloud vendor metadata via endpoints such as these via [our utilization configuration options](https://docs.newrelic.com/docs/agents/ruby-agent/configuration/ruby-agent-configuration#utilization-detect_aws).

Thanks for reaching out, and let me know if this helps.

**Comment by mehyedes** [comment]
Thank you for the link @rachelleahklein , I did not know about those options.
Will make sure to configure them to avoid this behavior.
