### ISSUE TITLE
Enabling newrelic cause Rails master to crash on boot

### ISSUE THREAD

**Issue by casperisfine** [newrelic/rpm#336]
Using the latest gem: 6.10.0.364
Using Rails cdbce035a5b0

It crashes like this during boot:

```
/artifacts/ruby/2.7.0/bundler/gems/rails-cdbce035a5b0/activerecord/lib/active_record/railtie.rb:190:in `block (2 levels) in <class:Railtie>': undefined method `delete' for nil:NilClass (NoMethodError)
    from /artifacts/ruby/2.7.0/bundler/gems/rails-cdbce035a5b0/activesupport/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
    from /artifacts/ruby/2.7.0/bundler/gems/rails-cdbce035a5b0/activesupport/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
    from /artifacts/ruby/2.7.0/bundler/gems/rails-cdbce035a5b0/activesupport/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
    from /artifacts/ruby/2.7.0/bundler/gems/rails-cdbce035a5b0/activesupport/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
    from /artifacts/ruby/2.7.0/bundler/gems/rails-cdbce035a5b0/activesupport/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
    from /artifacts/ruby/2.7.0/bundler/gems/rails-cdbce035a5b0/activesupport/lib/active_support/lazy_load_hooks.rb:51:in `each'
    from /artifacts/ruby/2.7.0/bundler/gems/rails-cdbce035a5b0/activesupport/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
```

This error suggest that the `ActiveSupport.on_load(:activerecord)` callback is executed twice: https://github.com/rails/rails/blob/cdbce035a5b0ebc779dd445888ab5670f945603c/activerecord/lib/active_record/railtie.rb#L186-L204

Note how the `config.activerecord.sqlite3` properly is removed, so it works fine on the first call, but fail if executed a second time.

I know for certain that NewRelic is the trigger as we enable it only on 1% of our pods, and it's only that 1% that was failing to boot.

It was also working fine with Rails v `9817d74f3be72d8e685301bfd0acb6a12b9cdda9`. So whatever changed is in this Rails diff: https://github.com/rails/rails/compare/9817d74f3be72d8e685301bfd0acb6a12b9cdda9...cdbce035a5b0ebc779dd445888ab5670f945603c

cc @rafaelfranca @etiennebarrie

**Comment by casperisfine** [comment]
I bisected the problem, and it seems to be introduced by https://github.com/rails/rails/commit/1a3dc42c172863fc2db24e9813203d2e793a9e2a. 

So it's very likely the problem is in Rails not New Relic. I'll close for now. Sorry.

**Comment by casperisfine** [comment]
For posterity in case someone find this issue, the root cause was that our `config.secret_key_base` was set too late.

Enabling NewRelic cause Active Record to be loaded earlier than normal, and turning in a cascading failure. Moving `config.secret_key_base = ` in `application.rb` solved this.
