### ISSUE TITLE
NoMethodError with mongoid 

### ISSUE THREAD

**Issue by cesarizu** [newrelic/rpm#345]
We are seeing lots of errors like these ones that are crashing our app:

```
** [NewRelic][2020-06-10 21:47:12 +0000 scheduler.* (4)] ERROR : NoMethodError: undefined method `reply' for #<Mongo::Monitoring::Event::CommandFailed:0x00007f3929cdaed8>
** [NewRelic][2020-06-14 01:18:02 +0000 worker.1 (4)] ERROR : NoMethodError: undefined method `descendant_complete' for nil:NilClass
```

The `reply` error seems to come from these files:

```
app/worker.1 /app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.11.0.365/lib/new_relic/agent/instrumentation/mongodb_command_subscriber.rb:25:in `error_present?'
app/worker.1 /app/vendor/bundle/ruby/2.6.0/gems/newrelic_rpm-6.11.0.365/lib/new_relic/agent/instrumentation/mongodb_command_subscriber.rb:34:in `completed'
```

Versions:
* newrelic_rpm (6.11.0.365)
* mongoid (6.4.2)
* mongo (2.12.1)

**Comment by mwlang** [comment]
The mongo gem changes its implementation of error reporting at version 2.6.0.
The agent was recently enhanced to report errors at span event level.

The two together leads to this specific issue.  There are two quick fixes that will resolve this immediately:
* downgrade mongo gem to 2.5.3
* downgrade ruby agent to 6.9.0.363 

Meanwhile, we will definitely be fixing the auto-instrumentation for mongo to support newer versions of the gem.

**Comment by mwlang** [comment]
* MongoDB instrumentation has been updated to cover 2.6 through 2.12
* The error reported above has also been addressed.
* These fixes will appear in the next release of the agent.

Until the fix is released, the following patch may be applied (typically by loading in a Rails initializers file:
~~~ruby
module NewRelic
  module Agent
    module Instrumentation
      class MongodbCommandSubscriber

        def error_key_present?(event)
          if reply = event.reply
            ERROR_KEYS.detect{ |key| reply[key] }
          end
        rescue => error
          false
        end

        def completed(event)
          begin
            return unless NewRelic::Agent::Tracer.tracing_enabled?
            segment = segments.delete(event.operation_id)
            return unless segment

            # operations that succeed buy have errors return CommandSucceeded 
            # with an error_key that is populated with error specfics
            if error_key = error_key_present?(event)
              # taking the last error as there can potentially be many
              attributes = event.reply[error_key][-1]
              segment.notice_error Mongo::Error.new("%s (%s)" % [attributes["errmsg"], attributes["code"]])

            # failing commands return a CommandFailed event with an error message
            # in the form of "% (%s)" for the message and code
            elsif event.is_a? Mongo::Monitoring::Event::CommandFailed
              segment.notice_error Mongo::Error.new(event.message)
            end
            segment.finish
          rescue Exception => e
            log_notification_error('completed', e)
          end
        end

      end
    end
  end
end
~~~
